controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    franka_robot_state_broadcaster:
      type: franka_ros2_control/FrankaRobotStateBroadcaster

    franka_gripper_controller:
      type: franka_gripper/FrankaGripperController
